import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <main>
      <Head>
        <title>CV Henri</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/cv.png" />
      </Head>
      <main >
      <div className="resume">
      <div className="resume_left">
        <div className="resume_profile">
          
          
        </div>
        <div className="resume_content">
          <div className="resume_item resume_info">
            <div className="title">
              <p className="bold_nom">Henri Mailly</p>
              <p className="regular">recherche de stage</p>
            </div>
            <ul>
              <li>
                <div className="icon">
                  <i className="fas fa-map-signs"></i>
                </div>
                <div className="data">
                  <a
                    >1 D rue Branly<br />
                    62510 Arques</a
                  >
                </div>
              </li>
              <li>
                <div className="icon">
                  <i className="fas fa-mobile-alt"></i>
                </div>
                <div className="data">06 63 23 63 88</div>
              </li>
              <li>
                <div className="icon">
                  <i className="fas fa-envelope"></i>
                </div>
                <div className="data">
                  <a href="mailto:henri.mailly@enigma-school.com"
                    >maillyhenri2004@gmail.com</a
                  >
                </div>
              </li>
              <li>
                <div className="icon">
                  <i className="fab fa-github"></i>
                </div>
                <div className="data">
                  <a href="https://github.com/Arhoverse">Github : Arhoverse</a>
                </div>
              </li>
            </ul>
          </div>
          <div className="resume_item resume_skills">
            <div className="title">
              <p className="bold">Compétences</p>
            </div>
            <ul>
              <li>
                <div className="skill_name">HTML,CSS</div>
              </li>
              <li>
                <div className="skill_name">Python</div>
              </li>
              <li>
                <div className="skill_name">JAVA</div>
              </li>
              <li>
                <div className="skill_name">JS</div>
              </li>
              <li>
                <div className="skill_name">SQL</div>
              </li>
              <li>
                <div className="skill_name">C</div>
              </li>
              <li>
                <div className="skill_name">CCNA2</div>
              </li>
              <li>
                <div className="skill_name">GESTION DE PROJET</div>
              </li>
              <li>
                <div className="skill_name">JEUX VIDEO</div>
              </li>
            </ul>
          </div>
          <div className="resume_item resume_social">
            <div className="title">
              <p className="bold">Social</p>
            </div>
            <ul>
              <li>
                <div className="icon">
                  <i className="fab fa-instagram-square"></i>
                </div>
                <div className="data">
                  <p className="semi-bold">Instagram</p>
                  <p>
                    <a href="https://www.instagram.com/henri.cfx/"
                      >henri.cfx</a
                    >
                  </p>
                </div>
              </li>

              <li>
                <div className="icon">
                  <i className="fab fa-linkedin"></i>
                </div>
                <div className="data">
                  <p className="semi-bold">Linkedin</p>
                  <p>
                    <a
                      href="https://www.linkedin.com/in/henri-mailly-a72536252/"
                      >Henri Mailly</a
                    >
                  </p>
                </div>
              </li>
            </ul>
          </div>
          <div className="title">
            <p className="bold">Qualités</p>
          </div>
          <div className="interet">
            <ul className="centres-interet">
              <li>
                <div className="skill_name">Dynamique</div>
              </li>
              <li>
                <div className="skill_name">Authentique</div>
              </li>
              <li>
                <div className="skill_name">Bonne ambiance</div>
              </li>
              <br />
            </ul>
          </div>
        </div>
      </div>

      <div className="resume_right">
        <div className="resume_item resume_about">
          <div className="title">
            <p className="bold">Étudiant en informatique</p>
          </div>
          <p>
          Étudiant en informatique passionné par le développement, à la recherche d'un stage pour acquérir une expérience concrète. Intérêt pour la programmation (Java, Python, C, JavaScript, HTML, CSS) et maîtrise des outils (Git, Visual Studio Code, Jet Brains…). Motivé pour travailler sur des projets innovants et collaborer avec des professionnels de l'informatique expérimentés. Convaincu que ce stage me permettra d'acquérir de nouvelles compétences et de contribuer de manière significative au succès de votre entreprise.
          </p>
          <br />
        </div>
        <div className="resume_item resume_work">
          <div className="title">
            <br />
            <p className="bold">Experience professionelle</p>
          </div>
          <ul>
            <li>
              <div className="date">2022</div>
              <div className="info">
                <p className="semi-bold">JOB D’ETE</p>
                <p>SERRES A TOMATES DES HDF</p>
                <p>
                Salarié aux Serres des Hauts de France : serres de culture de tomates : cueillette et logistique.
                </p>
              </div>
            </li>
            <li>
              <div className="date">2019-2020</div>
              <div className="info">
                <p className="semi-bold">
                BENEVOLE
                </p>
                <p>ESA TENNIS</p>
                <p>Assistant éducateur à l’école de tennis de
                  l’ESA Tennis à Arques : encadrement des
                  6-8 ans le samedi matin (Niveau 30/0).</p>

              </div>
            </li>
            <li>
              <div className="date">2018</div>
              <div className="info">
                <p className="semi-bold">STAGE DE 3ème</p>
                <p className="logotravail"></p>
                <p>
                CAPSO
                </p>
                <p>Stage de découverte en 4ème dans le service informatique de la CAPSO (Communauté d’Agglomération du Pays de Saint Omer) ; découverte du service et des métiers.</p>
                <br />
              </div>
            </li>
          </ul>
        </div>
        <div className="resume_item resume_education">
          <div className="title">
            <br />
            <p className="bold">Formations</p>
          </div>
          <ul>
            <li>
              <div className="date">En cours</div>
              <div className="info">
                <p className="semi-bold">BAC +3 Responsable de projet informatique</p>
                <p>École supérieure dinformatique</p>
                <p>Enigma</p>
              </div>
            </li>
            <li>
              <div className="date">2021-2022</div>
              <div className="info">
                <p className="semi-bold">BACCALAUREAT NSI/MATHS</p>
                <p>Lycée Alexandre Ribot</p>
                <br />
              </div>
            </li>
          </ul>
        </div>
        <div className="resume_item resume_hobby">
          <div className="title">
            <br />
            <p className="bold">Centre dintérêt</p>
            <br />
          </div>
          <ul>
            <p>Musculation</p>
            <p>Jeux vidéos</p>
            <p>Streamer Twitch</p>
            <p>Permis B</p>
          </ul>
        </div>
      </div>
    </div>
      </main>
    </main>
  )

}
